import type { Metadata } from 'next';
import Link from 'next/link';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // ⚠️ 주의: html과 body 태그는 오직 'Root Layout'에만 존재해야 합니다!
    <html lang="en">
      <body>
        {/* 1. 네비게이션 바: 여기에 배치하면 모든 페이지에서 유지됩니다. */}
        <nav className="p-4 bg-gray-100 flex gap-x-2">
          <Link href="/dashboard">대시보드</Link>
          <Link href="/products">프로덕트</Link>
        </nav>

        {/* 2. Main Content: 우리가 만든 page.tsx가 이 'children' 자리에 렌더링됩니다. */}
        <main>{children}</main>

        {/* 3. 푸터: 여기에 배치하면 모든 페이지 하단에 고정됩니다. */}
        <footer className="p-4 bg-gray-800 text-white">
          My Footer (공통 영역)
        </footer>
      </body>
    </html>
  );
}
